name: Deploy Go Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOY_USER: 'nn'
      DEPLOY_HOST: 'nn-ubuntu'
      DEPLOY_PATH: '/home/nn/go_apps'
      REPO_URL: 'https://github.com/novrian6/api_go_jenkins_demo.git'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cleanup and Clone Repository
        run: |
          echo "Cleaning up old files..."
          rm -rf api_go_jenkins_demo

          echo "Cloning the repository..."
          git clone ${{ env.REPO_URL }}

      - name: Build Application
        run: |
          echo "Building the Go application..."
          cd api_go_jenkins_demo && go build -o app main.go

      - name: Prepare Remote Deployment
        run: |
          echo "Stopping existing application and preparing deployment path..."
          ssh -o StrictHostKeyChecking=no ${{ env.DEPLOY_USER }}@${{ env.DEPLOY_HOST }} "
            pkill app || true;
            rm -f ${DEPLOY_PATH}/app;
            mkdir -p ${DEPLOY_PATH};
            chmod 755 ${DEPLOY_PATH}
          "

      - name: Deploy to Server
        run: |
          echo "Deploying the application to the server..."
          scp -o StrictHostKeyChecking=no api_go_jenkins_demo/app ${{ env.DEPLOY_USER }}@${{ env.DEPLOY_HOST }}:${{ env.DEPLOY_PATH }}

      - name: Set Permissions and Restart Application
        run: |
          echo "Setting execute permission and restarting the application..."
          ssh -o StrictHostKeyChecking=no ${{ env.DEPLOY_USER }}@${{ env.DEPLOY_HOST }} "
            chmod +x ${DEPLOY_PATH}/app;
            nohup ${DEPLOY_PATH}/app >/dev/null 2>&1 &
          "

      - name: Deployment Complete
        if: success()
        run: echo "Deployment completed successfully."
